spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/profile?useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
      password: 1111
      username: root
  devtools:
    livereload:
      enabled: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    hibernate:
    
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLInnoDBDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    show-sql: true
  thymeleaf:
    cache: false

mybatis:
  type-aliases-package: profile.back.mapper.*Mapper
  mapper-locations: classpath:/mapper/*Mapper.xml
  