spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      driver-class-name: ${spring.datasource.driver-class-name}
      jdbc-url: jdbc:mysql://localhost:3306/profile?useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
      password: 1111
      username: root
    password: 1111
    url: jdbc:mysql://localhost:3306/profile?useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
  devtools:
    livereload:
      enabled: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLInnoDBDialect
        enable_lazy_load_no_trans: true
        format_sql: true
        use_sql_comments: true
    show-sql: true
  thymeleaf:
    cache: false
